[package]
name = "rumipsem"
version = "0.1.0"
authors = ["Vasek Sraier <git@vakabus.cz>"]

[dependencies]
goblin = '*'
#sc = { git = "https://github.com/japaric/syscall.rs" }
libc = '*'
log = '*'
#simplelog = '*'
simple_logger = '*'
serde = '*'
serde_json = '*'
serde_derive = '*'
flate2 = '*'